### ISSUE TITLE
windows インストール、できません

### ISSUE THREAD

**Issue by john-banjirou** [mjx-project/mjx#1151]
以下、ログです。

お忙しいとは存じますが、何卒宜しくお願い致します。m(__)m
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------

(pythonProject1-mjmix) PS C:\Users\takada\PycharmProjects\pythonProject1-mjmix> pip install mjx                    
Collecting mjx
  Using cached mjx-0.1.0.tar.gz (354 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pillow
  Using cached Pillow-9.3.0-cp310-cp310-win_amd64.whl (2.5 MB)
Collecting grpcio==1.39.0
  Using cached grpcio-1.39.0.tar.gz (21.3 MB)
  Preparing metadata (setup.py) ... done
Collecting svgwrite
  Using cached svgwrite-1.4.3-py3-none-any.whl (67 kB)
Collecting protobuf==3.17.3
  Using cached protobuf-3.17.3-py2.py3-none-any.whl (173 kB)
Collecting numpy
  Using cached numpy-1.23.4-cp310-cp310-win_amd64.whl (14.6 MB)
Collecting google==3.0.0
  Using cached google-3.0.0-py2.py3-none-any.whl (45 kB)
Collecting inquirer
  Using cached inquirer-2.10.1-py3-none-any.whl (17 kB)
Collecting beautifulsoup4
  Using cached beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)
Collecting six>=1.5.2
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting readchar>=3.0.6
  Using cached readchar-4.0.3-py3-none-any.whl (8.4 kB)
Collecting blessed>=1.19.0
  Using cached blessed-1.19.1-py2.py3-none-any.whl (58 kB)
Collecting python-editor>=1.0.4
  Using cached python_editor-1.0.4-py3-none-any.whl (4.9 kB)
Collecting wcwidth>=0.1.4
  Using cached wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting jinxed>=1.1.0
  Using cached jinxed-1.2.0-py2.py3-none-any.whl (33 kB)
Requirement already satisfied: setuptools>=41.0 in c:\users\takada\.virtualenvs\pythonproject1-mjmix\lib\site-packages (from readchar>=3.0.6->inquirer->
mjx) (62.6.0)
Collecting soupsieve>1.2
  Using cached soupsieve-2.3.2.post1-py3-none-any.whl (37 kB)
Collecting ansicon
  Using cached ansicon-1.89.0-py2.py3-none-any.whl (63 kB)
Building wheels for collected packages: mjx, grpcio
  Building wheel for mjx (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for mjx (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [127 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\mjx
      copying .\mjx\action.py -> build\lib.win-amd64-cpython-310\mjx
      copying .\mjx\agents.py -> build\lib.win-amd64-cpython-310\mjx
      copying .\mjx\const.py -> build\lib.win-amd64-cpython-310\mjx
      copying .\mjx\env.py -> build\lib.win-amd64-cpython-310\mjx
      copying .\mjx\event.py -> build\lib.win-amd64-cpython-310\mjx
      copying .\mjx\hand.py -> build\lib.win-amd64-cpython-310\mjx
      copying .\mjx\observation.py -> build\lib.win-amd64-cpython-310\mjx
      copying .\mjx\open.py -> build\lib.win-amd64-cpython-310\mjx
      copying .\mjx\state.py -> build\lib.win-amd64-cpython-310\mjx
      copying .\mjx\tile.py -> build\lib.win-amd64-cpython-310\mjx
      copying .\mjx\utils.py -> build\lib.win-amd64-cpython-310\mjx
      copying .\mjx\__init__.py -> build\lib.win-amd64-cpython-310\mjx
      creating build\lib.win-amd64-cpython-310\mjxproto
      copying .\mjxproto\mjx_pb2.py -> build\lib.win-amd64-cpython-310\mjxproto
      copying .\mjxproto\mjx_pb2_grpc.py -> build\lib.win-amd64-cpython-310\mjxproto
      copying .\mjxproto\__init__.py -> build\lib.win-amd64-cpython-310\mjxproto
      creating build\lib.win-amd64-cpython-310\tests_py
      copying .\tests_py\test_action.py -> build\lib.win-amd64-cpython-310\tests_py
      copying .\tests_py\test_agents.py -> build\lib.win-amd64-cpython-310\tests_py
      copying .\tests_py\test_env.py -> build\lib.win-amd64-cpython-310\tests_py
      copying .\tests_py\test_event.py -> build\lib.win-amd64-cpython-310\tests_py
      copying .\tests_py\test_features.py -> build\lib.win-amd64-cpython-310\tests_py
      copying .\tests_py\test_hand.py -> build\lib.win-amd64-cpython-310\tests_py
      copying .\tests_py\test_observation.py -> build\lib.win-amd64-cpython-310\tests_py
      copying .\tests_py\test_state.py -> build\lib.win-amd64-cpython-310\tests_py
      copying .\tests_py\test_svgwrite.py -> build\lib.win-amd64-cpython-310\tests_py
      copying .\tests_py\test_tile.py -> build\lib.win-amd64-cpython-310\tests_py
      copying .\tests_py\test_visualizer.py -> build\lib.win-amd64-cpython-310\tests_py
      copying .\tests_py\_test_cli_selector.py -> build\lib.win-amd64-cpython-310\tests_py
      copying .\tests_py\__init__.py -> build\lib.win-amd64-cpython-310\tests_py
      creating build\lib.win-amd64-cpython-310\mjx\visualizer
      copying .\mjx\visualizer\converter.py -> build\lib.win-amd64-cpython-310\mjx\visualizer
      copying .\mjx\visualizer\selector.py -> build\lib.win-amd64-cpython-310\mjx\visualizer
      copying .\mjx\visualizer\svg.py -> build\lib.win-amd64-cpython-310\mjx\visualizer
      copying .\mjx\visualizer\visualizer.py -> build\lib.win-amd64-cpython-310\mjx\visualizer
      copying .\mjx\visualizer\__init__.py -> build\lib.win-amd64-cpython-310\mjx\visualizer
      running egg_info
      writing mjx.egg-info\PKG-INFO
      writing dependency_links to mjx.egg-info\dependency_links.txt
      writing requirements to mjx.egg-info\requires.txt
      writing top-level names to mjx.egg-info\top_level.txt
      reading manifest file 'mjx.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'mjx.egg-info\SOURCES.txt'
      copying .\mjx\visualizer\1000.svg -> build\lib.win-amd64-cpython-310\mjx\visualizer
      copying .\mjx\visualizer\1000_mini.svg -> build\lib.win-amd64-cpython-310\mjx\visualizer
      copying .\mjx\visualizer\100_mini.svg -> build\lib.win-amd64-cpython-310\mjx\visualizer
      copying .\mjx\visualizer\GL-MahjongTile.ttf -> build\lib.win-amd64-cpython-310\mjx\visualizer
      running build_ext
      -- Building for: NMake Makefiles
      CMake Error at CMakeLists.txt:2 (project):
        Generator
     
          NMake Makefiles
     
        does not support platform specification, but platform
     
          x64
     
        was specified.
     
     
      CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      See also "C:/Users/takada/AppData/Local/Temp/pip-install-qumip76f/mjx_7ef9cceae6634b9bb68390477009c038/build/temp.win-amd64-cpython-310/Release/CM
akeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>  
          main()
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main      
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 249, in build_whee
l
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\takada\AppData\Local\Temp\pip-build-env-vo_hn6xc\overlay\Lib\site-packages\setuptools\build_meta.py", line 412, in build_wheel   
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "C:\Users\takada\AppData\Local\Temp\pip-build-env-vo_hn6xc\overlay\Lib\site-packages\setuptools\build_meta.py", line 397, in _build_with_te
mp_dir
          self.run_setup()
        File "C:\Users\takada\AppData\Local\Temp\pip-build-env-vo_hn6xc\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup     
          exec(code, locals())
        File "<string>", line 138, in <module>
        File "C:\Users\takada\AppData\Local\Temp\pip-build-env-vo_hn6xc\overlay\Lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\takada\AppData\Local\Temp\pip-build-env-vo_hn6xc\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup    
          return run_commands(dist)
        File "C:\Users\takada\AppData\Local\Temp\pip-build-env-vo_hn6xc\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_comma
nds
          dist.run_commands()
        File "C:\Users\takada\AppData\Local\Temp\pip-build-env-vo_hn6xc\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_comma
nds
          self.run_command(cmd)
        File "C:\Users\takada\AppData\Local\Temp\pip-build-env-vo_hn6xc\overlay\Lib\site-packages\setuptools\dist.py", line 1217, in run_command        
          super().run_command(command)
        File "C:\Users\takada\AppData\Local\Temp\pip-build-env-vo_hn6xc\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_comma
nd
          cmd_obj.run()
        File "C:\Users\takada\AppData\Local\Temp\pip-build-env-vo_hn6xc\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "C:\Users\takada\AppData\Local\Temp\pip-build-env-vo_hn6xc\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_comman
d
          self.distribution.run_command(command)
        File "C:\Users\takada\AppData\Local\Temp\pip-build-env-vo_hn6xc\overlay\Lib\site-packages\setuptools\dist.py", line 1217, in run_command        
          super().run_command(command)
        File "C:\Users\takada\AppData\Local\Temp\pip-build-env-vo_hn6xc\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_comma
nd
          cmd_obj.run()
        File "C:\Users\takada\AppData\Local\Temp\pip-build-env-vo_hn6xc\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 132, in 
run
          self.run_command(cmd_name)
        File "C:\Users\takada\AppData\Local\Temp\pip-build-env-vo_hn6xc\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_comman
d
          self.distribution.run_command(command)
        File "C:\Users\takada\AppData\Local\Temp\pip-build-env-vo_hn6xc\overlay\Lib\site-packages\setuptools\dist.py", line 1217, in run_command        
          super().run_command(command)
        File "C:\Users\takada\AppData\Local\Temp\pip-build-env-vo_hn6xc\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_comma
nd
          cmd_obj.run()
        File "C:\Users\takada\AppData\Local\Temp\pip-build-env-vo_hn6xc\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 84, in run     
          _build_ext.run(self)
        File "C:\Users\takada\AppData\Local\Temp\pip-build-env-vo_hn6xc\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346,
 in run
          self.build_extensions()
        File "C:\Users\takada\AppData\Local\Temp\pip-build-env-vo_hn6xc\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 466,
 in build_extensions
          self._build_extensions_serial()
        File "C:\Users\takada\AppData\Local\Temp\pip-build-env-vo_hn6xc\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 492,
 in _build_extensions_serial
          self.build_extension(ext)
        File "<string>", line 129, in build_extension
        File "C:\Users\takada\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\takada\\AppData\\Local\\Temp\\pip-install-qumip76f\\mjx_7ef9cceae6634b9bb68390477009
c038', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\takada\\AppData\\Local\\Temp\\pip-install-qumip76f\\mjx_7ef9cceae6634b9bb68390477009c038\\build\\lib
.win-amd64-cpython-310\\', '-DPYTHON_EXECUTABLE=C:\\Users\\takada\\.virtualenvs\\pythonProject1-mjmix\\Scripts\\python.exe', '-DCMAKE_BUILD_TYPE=Release
', '-DMJX_BUILD_TESTS=OFF', '-DMJX_BUILD_PYTHON=ON', '-DMJX_BUILD_BOOST=ON', '-DMJX_BUILD_GRPC=ON', '-A', 'x64', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEA
SE=C:\\Users\\takada\\AppData\\Local\\Temp\\pip-install-qumip76f\\mjx_7ef9cceae6634b9bb68390477009c038\\build\\lib.win-amd64-cpython-310\\']' returned n
on-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mjx
  Building wheel for grpcio (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [180 lines of output]
      ASM Builds for BoringSSL currently not supported on: win-amd64
      Found cython-generated files...
      running bdist_wheel
      running build
      running build_py
      running build_project_metadata
      creating python_build
      creating python_build\lib.win-amd64-cpython-310
      creating python_build\lib.win-amd64-cpython-310\grpc
      copying src\python\grpcio\grpc\_auth.py -> python_build\lib.win-amd64-cpython-310\grpc
      copying src\python\grpcio\grpc\_channel.py -> python_build\lib.win-amd64-cpython-310\grpc
      copying src\python\grpcio\grpc\_common.py -> python_build\lib.win-amd64-cpython-310\grpc
      copying src\python\grpcio\grpc\_compression.py -> python_build\lib.win-amd64-cpython-310\grpc
      copying src\python\grpcio\grpc\_grpcio_metadata.py -> python_build\lib.win-amd64-cpython-310\grpc
      copying src\python\grpcio\grpc\_interceptor.py -> python_build\lib.win-amd64-cpython-310\grpc
      copying src\python\grpcio\grpc\_plugin_wrapping.py -> python_build\lib.win-amd64-cpython-310\grpc
      copying src\python\grpcio\grpc\_runtime_protos.py -> python_build\lib.win-amd64-cpython-310\grpc
      copying src\python\grpcio\grpc\_server.py -> python_build\lib.win-amd64-cpython-310\grpc
      copying src\python\grpcio\grpc\_simple_stubs.py -> python_build\lib.win-amd64-cpython-310\grpc
      copying src\python\grpcio\grpc\_utilities.py -> python_build\lib.win-amd64-cpython-310\grpc
      copying src\python\grpcio\grpc\__init__.py -> python_build\lib.win-amd64-cpython-310\grpc
      creating python_build\lib.win-amd64-cpython-310\grpc\aio
      copying src\python\grpcio\grpc\aio\_base_call.py -> python_build\lib.win-amd64-cpython-310\grpc\aio
      copying src\python\grpcio\grpc\aio\_base_channel.py -> python_build\lib.win-amd64-cpython-310\grpc\aio
      copying src\python\grpcio\grpc\aio\_base_server.py -> python_build\lib.win-amd64-cpython-310\grpc\aio
      copying src\python\grpcio\grpc\aio\_call.py -> python_build\lib.win-amd64-cpython-310\grpc\aio
      copying src\python\grpcio\grpc\aio\_channel.py -> python_build\lib.win-amd64-cpython-310\grpc\aio
      copying src\python\grpcio\grpc\aio\_interceptor.py -> python_build\lib.win-amd64-cpython-310\grpc\aio
      copying src\python\grpcio\grpc\aio\_metadata.py -> python_build\lib.win-amd64-cpython-310\grpc\aio
      copying src\python\grpcio\grpc\aio\_server.py -> python_build\lib.win-amd64-cpython-310\grpc\aio
      copying src\python\grpcio\grpc\aio\_typing.py -> python_build\lib.win-amd64-cpython-310\grpc\aio
      copying src\python\grpcio\grpc\aio\_utils.py -> python_build\lib.win-amd64-cpython-310\grpc\aio
      copying src\python\grpcio\grpc\aio\__init__.py -> python_build\lib.win-amd64-cpython-310\grpc\aio
      creating python_build\lib.win-amd64-cpython-310\grpc\beta
      copying src\python\grpcio\grpc\beta\implementations.py -> python_build\lib.win-amd64-cpython-310\grpc\beta
      copying src\python\grpcio\grpc\beta\interfaces.py -> python_build\lib.win-amd64-cpython-310\grpc\beta
      copying src\python\grpcio\grpc\beta\utilities.py -> python_build\lib.win-amd64-cpython-310\grpc\beta
      copying src\python\grpcio\grpc\beta\_client_adaptations.py -> python_build\lib.win-amd64-cpython-310\grpc\beta
      copying src\python\grpcio\grpc\beta\_metadata.py -> python_build\lib.win-amd64-cpython-310\grpc\beta
      copying src\python\grpcio\grpc\beta\_server_adaptations.py -> python_build\lib.win-amd64-cpython-310\grpc\beta
      copying src\python\grpcio\grpc\beta\__init__.py -> python_build\lib.win-amd64-cpython-310\grpc\beta
      creating python_build\lib.win-amd64-cpython-310\grpc\experimental
      copying src\python\grpcio\grpc\experimental\gevent.py -> python_build\lib.win-amd64-cpython-310\grpc\experimental
      copying src\python\grpcio\grpc\experimental\session_cache.py -> python_build\lib.win-amd64-cpython-310\grpc\experimental
      copying src\python\grpcio\grpc\experimental\__init__.py -> python_build\lib.win-amd64-cpython-310\grpc\experimental
      creating python_build\lib.win-amd64-cpython-310\grpc\framework
      copying src\python\grpcio\grpc\framework\__init__.py -> python_build\lib.win-amd64-cpython-310\grpc\framework
      creating python_build\lib.win-amd64-cpython-310\grpc\_cython
      copying src\python\grpcio\grpc\_cython\__init__.py -> python_build\lib.win-amd64-cpython-310\grpc\_cython
      creating python_build\lib.win-amd64-cpython-310\grpc\experimental\aio
      copying src\python\grpcio\grpc\experimental\aio\__init__.py -> python_build\lib.win-amd64-cpython-310\grpc\experimental\aio
      creating python_build\lib.win-amd64-cpython-310\grpc\framework\common
      copying src\python\grpcio\grpc\framework\common\cardinality.py -> python_build\lib.win-amd64-cpython-310\grpc\framework\common
      copying src\python\grpcio\grpc\framework\common\style.py -> python_build\lib.win-amd64-cpython-310\grpc\framework\common
      copying src\python\grpcio\grpc\framework\common\__init__.py -> python_build\lib.win-amd64-cpython-310\grpc\framework\common
      creating python_build\lib.win-amd64-cpython-310\grpc\framework\foundation
      copying src\python\grpcio\grpc\framework\foundation\abandonment.py -> python_build\lib.win-amd64-cpython-310\grpc\framework\foundation
      copying src\python\grpcio\grpc\framework\foundation\callable_util.py -> python_build\lib.win-amd64-cpython-310\grpc\framework\foundation
      copying src\python\grpcio\grpc\framework\foundation\future.py -> python_build\lib.win-amd64-cpython-310\grpc\framework\foundation
      copying src\python\grpcio\grpc\framework\foundation\logging_pool.py -> python_build\lib.win-amd64-cpython-310\grpc\framework\foundation
      copying src\python\grpcio\grpc\framework\foundation\stream.py -> python_build\lib.win-amd64-cpython-310\grpc\framework\foundation
      copying src\python\grpcio\grpc\framework\foundation\stream_util.py -> python_build\lib.win-amd64-cpython-310\grpc\framework\foundation
      copying src\python\grpcio\grpc\framework\foundation\__init__.py -> python_build\lib.win-amd64-cpython-310\grpc\framework\foundation
      creating python_build\lib.win-amd64-cpython-310\grpc\framework\interfaces
      copying src\python\grpcio\grpc\framework\interfaces\__init__.py -> python_build\lib.win-amd64-cpython-310\grpc\framework\interfaces
      creating python_build\lib.win-amd64-cpython-310\grpc\framework\interfaces\base
      copying src\python\grpcio\grpc\framework\interfaces\base\base.py -> python_build\lib.win-amd64-cpython-310\grpc\framework\interfaces\base
      copying src\python\grpcio\grpc\framework\interfaces\base\utilities.py -> python_build\lib.win-amd64-cpython-310\grpc\framework\interfaces\base    
      copying src\python\grpcio\grpc\framework\interfaces\base\__init__.py -> python_build\lib.win-amd64-cpython-310\grpc\framework\interfaces\base     
      creating python_build\lib.win-amd64-cpython-310\grpc\framework\interfaces\face
      copying src\python\grpcio\grpc\framework\interfaces\face\face.py -> python_build\lib.win-amd64-cpython-310\grpc\framework\interfaces\face
      copying src\python\grpcio\grpc\framework\interfaces\face\utilities.py -> python_build\lib.win-amd64-cpython-310\grpc\framework\interfaces\face    
      copying src\python\grpcio\grpc\framework\interfaces\face\__init__.py -> python_build\lib.win-amd64-cpython-310\grpc\framework\interfaces\face     
      creating python_build\lib.win-amd64-cpython-310\grpc\_cython\_cygrpc
      copying src\python\grpcio\grpc\_cython\_cygrpc\__init__.py -> python_build\lib.win-amd64-cpython-310\grpc\_cython\_cygrpc
      creating python_build\lib.win-amd64-cpython-310\grpc\_cython\_credentials
      copying src\python\grpcio\grpc\_cython\_credentials\roots.pem -> python_build\lib.win-amd64-cpython-310\grpc\_cython\_credentials
      running build_ext
      Non-fatal exception:Traceback (most recent call last):
        File "C:\Users\takada\AppData\Local\Temp\pip-install-qumip76f\grpcio_509305e94db14673ad10453cfb9c2348\src\python\grpcio\commands.py", line 237, 
in compiler_ok_with_extra_std
          cc_test = subprocess.Popen(['cc', '-x', 'c', '-std=c++11', '-'],
        File "C:\Users\takada\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\takada\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] 指定されたファイルが見つかりません。
     
      Found cython-generated files...
      building 'grpc._cython.cygrpc' extension
      Traceback (most recent call last):
        File "C:\Users\takada\AppData\Local\Temp\pip-install-qumip76f\grpcio_509305e94db14673ad10453cfb9c2348\src\python\grpcio\commands.py", line 286, 
in build_extensions
          build_ext.build_ext.build_extensions(self)
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 459, in build_extens
ions
          self._build_extensions_serial()
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 485, in _build_exten
sions_serial
          self.build_extension(ext)
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension        
          _build_ext.build_extension(self, ext)
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 540, in build_extens
ion
          objects = self.compiler.compile(
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 361, in compile
          self.initialize()
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 241, in initialize      
          vc_env = _get_vc_env(plat_spec)
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\setuptools\msvc.py", line 270, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError(
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visual
studio.microsoft.com/visual-cpp-build-tools/
     
      During handling of the above exception, another exception occurred:
     
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\takada\AppData\Local\Temp\pip-install-qumip76f\grpcio_509305e94db14673ad10453cfb9c2348\setup.py", line 526, in <module>
          setuptools.setup(
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\setuptools\_distutils\core.py", line 177, in setup
          return run_commands(dist)
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\setuptools\_distutils\core.py", line 193, in run_commands
          dist.run_commands()
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\setuptools\dist.py", line 1229, in run_command
          super().run_command(command)
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\setuptools\_distutils\cmd.py", line 317, in run_command
          self.distribution.run_command(command)
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\setuptools\dist.py", line 1229, in run_command
          super().run_command(command)
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\setuptools\command\build.py", line 24, in run
          super().run()
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\setuptools\_distutils\cmd.py", line 317, in run_command
          self.distribution.run_command(command)
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\setuptools\dist.py", line 1229, in run_command
          super().run_command(command)
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
          _build_ext.run(self)
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
          self.build_extensions()
        File "C:\Users\takada\AppData\Local\Temp\pip-install-qumip76f\grpcio_509305e94db14673ad10453cfb9c2348\src\python\grpcio\commands.py", line 289, 
in build_extensions
          support.diagnose_build_ext_error(self, error, formatted_exception)
        File "C:\Users\takada\AppData\Local\Temp\pip-install-qumip76f\grpcio_509305e94db14673ad10453cfb9c2348\src\python\grpcio\support.py", line 111, i
n diagnose_build_ext_error
          raise commands.CommandError(
      commands.CommandError:
     
      We could not diagnose your build failure. If you are unable to proceed, please file an issue at http://www.github.com/grpc/grpc with `[Python inst
all]` in the title; please attach the whole log (including everything that may have appeared above the Python backtrace).
     
      Traceback (most recent call last):
        File "C:\Users\takada\AppData\Local\Temp\pip-install-qumip76f\grpcio_509305e94db14673ad10453cfb9c2348\src\python\grpcio\commands.py", line 286, 
in build_extensions
          build_ext.build_ext.build_extensions(self)
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 459, in build_extens
ions
          self._build_extensions_serial()
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 485, in _build_exten
sions_serial
          self.build_extension(ext)
        File "C:\Users\takada\.virtualenvs\pythonProject1-mjmix\lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension        

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for grpcio
  Running setup.py clean for grpcio
Failed to build mjx grpcio
ERROR: Could not build wheels for mjx, which is required to install pyproject.toml-based projects
(pythonProject1-mjmix) PS C:\Users\takada\PycharmProjects\pythonProject1-mjmix>
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------

**Comment by john-banjirou** [comment]
Currently Windows and macOS Apple Silicon are NOT supported.

でしたか。
失礼しました。
